[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.8.1"

[[bin]]
name = "darwinia"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
# crates
futures         = { version = "0.3.7" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }
# darwinia
darwinia-cli     = { path = "cli" }
darwinia-service = { path = "node/service" }

[dev-dependencies]
assert_cmd = { version = "1.0.1" }
nix        = { version = "0.19.0" }
tempfile   = { version = "3.1.0" }

[features]
default = ["darwinia-cli/wasmtime"]
dev     = [
	"darwinia-service/dev",
	"darwinia-cli/dev",
]

[workspace]
members = [
	"cli",
	"primitives",
	"rpc",
	"runtime/common",
	"runtime/crab",
	"runtime/darwinia",
	"node/service",
]

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"

[patch.'https://github.com/darwinia-network/substrate']
frame-support              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
frame-system               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-authority-discovery = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-authorship          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-evm                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-im-online           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-session             = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-timestamp           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sc-client-api              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sc-client-db               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sc-transaction-pool        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-api                     = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-application-crypto      = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-arithmetic              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-authority-discovery     = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-authorship              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-blockchain              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-babe          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-slots         = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-vrf           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-core                    = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-externalities           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-finality-grandpa        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-inherents               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-io                      = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-runtime                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-session                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-staking                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-state-machine           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-storage                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-timestamp               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-transaction-pool        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-trie                    = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-utils                   = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-version                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-wasm-interface          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }